# AOD Data Extraction

In [9]:
import geemap
import ee
ee.Initialize()
import pandas as pd

In [2]:
Map = geemap.Map(center = [53.35, -6.28], zoom=4)
Map

Map(center=[53.35, -6.28], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=HBox(childre…

In [3]:
roi = ee.Geometry.Point(-6.28, 53.35 ).buffer(2000)
Map.addLayer(roi)
Map

Map(bottom=956.0, center=[54.166088923680576, 0.12985673160382574], controls=(WidgetControl(options=['position…

In [4]:
AOD = ee.ImageCollection('MODIS/006/MCD19A2_GRANULES').filterDate('2020-05-01', '2020-05-31')

In [5]:
def roi_mean(img):
    mean = img.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi, scale=100).get('Optical_Depth_055')
    return img.set('date', img.date().format()).set('mean',mean)

In [6]:
roi_reduced_imgs = AOD.map(roi_mean)

In [7]:
imgs_list = roi_reduced_imgs.reduceColumns(ee.Reducer.toList(2), ['date','mean']).values().get(0)

In [10]:
df = pd.DataFrame(imgs_list.getInfo(), columns=['date','mean'])
#df

In [11]:
df['date'] = pd.to_datetime(df['date'])

df = df.set_index('date')
df

                           mean
date
2020-05-01 11:55:00  211.461714
2020-05-01 12:10:00  194.033063
2020-05-02 12:40:00  194.000000
2020-05-03 11:45:00   21.323121
2020-05-03 13:35:00   43.628214
2020-05-04 10:50:00  170.498940
2020-05-04 12:30:00  120.271901
2020-05-04 12:40:00   93.526073
2020-05-04 14:15:00   24.635568
2020-05-05 11:35:00  140.818856
2020-05-05 13:20:00   47.929539
2020-05-06 10:35:00   39.951126
2020-05-06 12:15:00   24.402256
2020-05-06 12:25:00   62.729025
2020-05-06 14:05:00   25.669503
2020-05-08 12:05:00  107.400499
2020-05-08 12:15:00  110.191949
2020-05-08 13:50:00  157.897546
2020-05-09 11:10:00   97.787897
2020-05-09 12:45:00  124.132692
2020-05-09 12:55:00  202.587572
2020-05-11 12:35:00   17.917801
2020-05-11 12:45:00   51.504558
2020-05-11 14:20:00   21.668862
2020-05-13 12:20:00  291.894309
2020-05-13 12:35:00  198.852774
2020-05-13 14:10:00  101.581880
2020-05-14 11:25:00   59.172056
2020-05-14 13:15:00   31.788165
2020-05-19 13:35:00  416.000000
2020-05-22 10:35:00  286.034471
2020-05-24 12:05:00  250.646559
2020-05-24 13:50:00   78.064000
2020-05-25 11:10:00  145.989690
2020-05-26 11:50:00  197.580498
2020-05-26 12:00:00  174.109847
2020-05-26 13:40:00  260.402616
2020-05-27 10:55:00  216.141011
2020-05-27 12:45:00  231.609160
2020-05-27 14:20:00  156.933754
2020-05-28 11:40:00  206.211127
2020-05-29 10:45:00   92.355737
2020-05-29 12:35:00  188.439197